# Generated by Django 3.2.8 on 2021-10-12 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия пользователя')),
                ('country', models.CharField(blank=True, max_length=30, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=30, verbose_name='Улица')),
                ('url_users', models.URLField(blank=True, unique=True, verbose_name='URL пользователя')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо вводить в формате «+999999999» Допускается от 5 до 12 цифр.', regex='^\\+?1?\\d{5,12}$')], verbose_name='Номер телефона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'unique_together': {('name', 'surname')},
            },
        ),
    ]
