# Generated by Django 3.2.8 on 2021-10-12 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Номер телефона необходимо вводить в формате «+999999999» Допускается от 5 до 12 цифр.', regex='^\\+?1?\\d{5,12}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='users',
            name='street',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='users',
            name='url_users',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='URL пользователя'),
        ),
    ]
