# Generated by Django 3.2.8 on 2021-10-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия пользователя')),
                ('country', models.CharField(max_length=30, null=True, verbose_name='Страна')),
                ('city', models.CharField(max_length=30, null=True, verbose_name='Город')),
                ('street', models.CharField(max_length=30, null=True, verbose_name='Улица')),
                ('url_users', models.URLField(blank=True, unique=True, verbose_name='URL пользователя')),
                ('phone', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
            options={
                'unique_together': {('name', 'surname')},
            },
        ),
    ]
